
// Clave BD: 5munpj2QDUYfgBKQ

RF10

SELECT INGRESO_SALIDA_AREA.ID_AREA, INGRESO_SALIDA_AREA.ID_CARGA, CARGA.DESTINO
FROM
    (
      SELECT CARGA.ID
      FROM CARGA JOIN DESTINOS_BUQUES ON CARGA.DESTINO = DESTINOS_BUQUES.DESTINO
      WHERE DESTINOS_BUQUES.DESTINO = ""
    )
    JOIN INGRESO_SALIDA_AREA ON INGRESO_SALIDA_AREA.ID_CARGA = CARGA.ID;


Datos de prueba:

JSON:
  {
      "id":"15"
  }
ID del buque a cargar

Datos necesarios en tablas:

BUQUE:
ID, NOMBRE, CAPACIDAD_DISPONIBLE, REGISTRO_CAPITANIA, AGENTE_MARITIMO, TIPO_BUQUE, ESTADO, CAPACIDAD_MAXIMA
15,BUQ3,30,RC3,AM3,MULTIPROPOSITO, NORMAL, 30

CARGA
ID, VOLUMEN, TIPO, ID_IMPORTADOR, DESTINO, ID_EXPORTADOR(AGREGAR COLUMNA)
24, 100, CONTENEDOR, NULL, PUERTOCARLOS, 1
25, 50, CONTENEDOR, NULL, PUERTOCARLOS, 1
26, 75, CONTENEDOR, NULL, PUERTOCARLOS, 2
27, 25, CONTENEDOR, NULL, PUERTOCARLOS, 3
28, 100, CONTENEDOR, NULL, PUERTODAVID, 10
29, 50, CONTENEDOR, NULL, PUERTODAVID, 2
30, 50, CONTENEDOR, NULL, PUERTOSISTRANS, 3

EXPORTADOR
ID, RUT
1, 11
2, 12
3, 13

DESTINOS_BUQUES
ID_BUQUE, DESTINO
15, PUERTOCARLOS
15, PUERTOSISTRANS

AREA
ID, CUARTO_FRIO, TIPO, ESTADO, CAPACIDAD_DISPONIBLE, CAPACIDAD_MAXIMA
8, 1, BODEGA, LIBERADA, 100, 100
9, 2, BODEGA, LIBERADA, 150, 150
10, 3, BODEGA, LIBERADA, 50, 50


INGRESO_SALIDA_AREA
ID, ID_CARGA, ID_AREA, VIENE_DE, FECHA_INGRESO, FECHA_SALIDA, ID_IMPORTADOR(ELIMINAR COLUMNA)
1, 24, 8, CAMION, 2016-01-01, NULL
2, 25, 10, CAMION, 2016-01-01, NULL
3, 26, 8, CAMION, 2016-01-01, NULL
4, 27, 9, CAMION, 2016-01-01, NULL
5, 28, 10, CAMION, 2016-01-01, NULL
6, 29, 8, CAMION, 2016-01-01, NULL
7, 30, 9, CAMION, 2016-01-01, NULL

AREA
ID, CUARTO_FRIO, TIPO, ESTADO, CAPACIDAD_DISPONIBLE, CAPACIDAD_MAXIMA
8, 1, BODEGA, LIBERADA, 97, 100
9, 2, BODEGA, LIBERADA, 148, 150
10, 3, BODEGA, LIBERADA, 48, 50

* AL SACARLAS SE DEBE ACTUALIZAR FECHA_SALIDA, LA CAPACIDAD_DISPONIBLE DE AREA Y DISMINUIR LA CAPACIDAD_DISPONIBLE DEL BUQUE

// TERMINACION EXITOSA

INGRESO_SALIDA_AREA
ID, ID_CARGA, ID_AREA, VIENE_DE, FECHA_INGRESO, FECHA_SALIDA, ID_IMPORTADOR(ELIMINAR COLUMNA)
1, 24, 8, CAMION, 2016-01-01, <HOY>
2, 25, 10, CAMION, 2016-01-01, <HOY>
3, 26, 8, CAMION, 2016-01-01, <HOY>
4, 27, 9, CAMION, 2016-01-01, <HOY>
5, 28, 10, CAMION, 2016-01-01, <HOY>
6, 29, 8, CAMION, 2016-01-01, <HOY>
7, 30, 9, CAMION, 2016-01-01, <HOY>

AREA
ID, CUARTO_FRIO, TIPO, ESTADO, CAPACIDAD_DISPONIBLE, CAPACIDAD_MAXIMA
8, 1, BODEGA, LIBERADA, 100, 100
9, 2, BODEGA, LIBERADA, 150, 150
10, 3, BODEGA, LIBERADA, 50, 50

ID, NOMBRE, CAPACIDAD_DISPONIBLE, REGISTRO_CAPITANIA, AGENTE_MARITIMO, TIPO_BUQUE, ESTADO, CAPACIDAD_MAXIMA
15,BUQ3,23,RC3,AM3,MULTIPROPOSITO, NORMAL, 30

ARGUMENTACION ACID: Las transacciones involucradas en el proceso de cargar un buque conservan las propiedades ACID dado que se implementan commits
para mantener la Atomicidad, y se trabaja bajo el esquema de NIVEL DE AISLAMIENTO SERIALIZABLE el cual no permite
insociestencias en las lecturas y ayuda a conservar la Coherencia de los datos.

///////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////

// RF13

Datos de prueba:

JSON:
  {
      "id":"15"
  }
ID del area a cerrar

Datos necesarios en tablas:

AREA
ID, CUARTO_FRIO, TIPO, ESTADO, CAPACIDAD_DISPONIBLE, CAPACIDAD_MAXIMA
13, 5, PATIO, LIBERADA, 40,40
14, NULL, PATIO, LIBERADA, 4, 20
15, NULL, PATIO, LIBERADA, 10, 15

CARGA
ID, VOLUMEN, TIPO, ID_IMPORTADOR, DESTINO, ID_EXPORTADOR(AGREGAR COLUMNA)
31, 10, GRANEL, NULL, PUERTOCARLOS, 2
32, 20, GRANEL, NULL, PUERTOCARLOS, 2
33, 30, GRANEL, NULL, PUERTOCARLOS, 2
34, 40, GRANEL, NULL, PUERTOCARLOS, 2
35, 50, GRANEL, NULL, PUERTOCARLOS, 2

INGRESO_SALIDA_AREA
ID, ID_CARGA, ID_AREA, VIENE_DE, FECHA_INGRESO, FECHA_SALIDA, ID_IMPORTADOR(ELIMINAR COLUMNA)
8, 31, 15, CAMION, 2016-02-02, NULL
9, 32, 15, CAMION, 2016-02-02, NULL
10, 33, 15, CAMION, 2016-02-02, NULL
11, 34, 15, CAMION, 2016-02-02, NULL
12, 35, 15, CAMION, 2016-02-02, NULL

// DESPUES DE CERRAR AREA 15 SE DEBE REGISTRAR FECHA_SALIDA, CAMBIAR ESTADO DE AREA 15 A DESHABILITADA, CAPACIDAD_DISPONIBLE A 15
Y LA CAPACIDAD_DISPONIBLE DE LAS AREAS Y REGISTRAR LOS INGRESOS

INGRESO_SALIDA_AREA
ID, ID_CARGA, ID_AREA, VIENE_DE, FECHA_INGRESO, FECHA_SALIDA, ID_IMPORTADOR(ELIMINAR COLUMNA)
8, 31, 15, CAMION, 2016-02-02, <HOY>
9, 32, 15, CAMION, 2016-02-02, <HOY>
10, 33, 15, CAMION, 2016-02-02, <HOY>
11, 34, 15, CAMION, 2016-02-02, <HOY>
12, 35, 15, CAMION, 2016-02-02, <HOY>

AREA
ID, CUARTO_FRIO, TIPO, ESTADO, CAPACIDAD_DISPONIBLE, CAPACIDAD_MAXIMA
13, 5, PATIO, LIBERADA, 39,40
14, NULL, PATIO, LIBERADA, 0, 20
15, NULL, PATIO, DESHABILITADA, 15, 15

INGRESO_SALIDA_AREA
ID, ID_CARGA, ID_AREA, VIENE_DE, FECHA_INGRESO, FECHA_SALIDA, ID_IMPORTADOR(ELIMINAR COLUMNA)
13, 31, 14, CAMION, <HOY>, NULL
14, 32, 14, CAMION, <HOY>, NULL
15, 33, 14, CAMION, <HOY>, NULL
16, 34, 14, CAMION, <HOY>, NULL
17, 35, 13, CAMION, <HOY>, NULL

ARGUMENTACION ACID: Las transacciones involucradas en el proceso de cerrar un area conservan las propiedades ACID dado que se implementan commits
para mantener la Atomicidad, y se trabaja bajo el esquema de NIVEL DE AISLAMIENTO SERIALIZABLE el cual no permite
insociestencias en las lecturas y ayuda a conservar la Coherencia de los datos.
-------------------------
RFC8 SQL
SELECT ISB.ID_BUQUE AS ID_BUQUE, B.NOMBRE AS NOMBRE, ISB.FECHA_INGRESO AS FECHA_INGRESO, ISB.FECHA_SALIDA AS FECHA_SALIDA, B.NOMBRE AS NOMBRE_BUQUE , B.TIPO_BUQUE AS TIPO_BUQUE
FROM INGRESO_SALIDA_BUQUES ISB INNER JOIN BUQUE B ON ISB.ID_BUQUE=B.ID
WHERE ISB.FECHA_INGRESO <=  TO_DATE('2017-01-03', 'YYYY-MM-DD')
AND ISB.FECHA_SALIDA >=  TO_DATE('2017-03-28', 'YYYY-MM-DD')
AND B.NOMBRE <> 'BUQ1041'
AND B.TIPO_BUQUE <> 'MULTIPROPOSITO';

CREATE INDEX IN_TIPO_BUQUE ON BUQUE(TIPO_BUQUE);

RFC10 SQL
SELECT ISA.ID_CARGA, ISA.ID_AREA, ISA.VIENE_DE, ISA.FECHA_INGRESO, ISA.FECHA_SALIDA, C.TIPO
FROM INGRESO_SALIDA_AREA ISA JOIN CARGA C ON ISA.ID_CARGA=C.ID
WHERE ISA.ID_AREA="" OR ISA.ID_AREA="";

--propuesta
SELECT ISA.ID_CARGA, ISA.ID_AREA, ISA.VIENE_DE, ISA.FECHA_INGRESO, ISA.FECHA_SALIDA, C.TIPO
FROM INGRESO_SALIDA_AREA ISA JOIN CARGA C ON ISA.ID_CARGA=C.ID
WHERE ISA.ID_AREA="" AND C.TIPO="";

CREATE INDEX IN_TIPO_CARGA ON CARGA(TIPO);
